### PR TITLE
Implemented notes

### PR DESCRIPTION
**Pull request by LinusPotocnik**
## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines](https://github.com/LIFEDEVELOPMENT/LiFeBot.js/blob/e36b4fe5d9941a4718d4a1a2a47f89faef313065/.github/CONTRIBUTING.md).

## Changes

- [x] Frontend
- [x] Backend
- [ ] Other: \_\_\_\_\_ 

Fixes NaN

### Summary:

- Created a command for storing key-value based notes (supports creating, deleting and querying them)

### New behaviour:

- New note command-group for the aforementioned features

### Changed behaviour:

- Added parameters for sql-queries. This can be used to simplify guildspecific sql queries in the future

### Removed behaviour:
- None

### CODE REVIEW

**Comment by LinusPotocnik** [comment]
Works

**Review by FelixThoben — APPROVED** [review]
Looks good!

**Review by LinusPotocnik — COMMENTED** [review]
Will quickly take a look at NoteUtility exports

**Review by LinusPotocnik — COMMENTED** [review]
Fine with that :D

**Pull request merged**
